'use strict';
// Narrative. Biographical detail follows clydetombaugh.com and Tombaugh & Moore, Out of the Darkness.
const TEXT = {
  intro: [
    { img: ['kansas_hail.jpg', 'portrait.jpg'], gray: true, lines: ['Clyde Tombaugh. Burdett, Kansas. Summer 1928.', 'He is twenty-two, with a high school diploma, a pick and a shovel.', 'A hailstorm flattens the wheat in twenty minutes.', 'With it goes the money for college.'] },
    { img: ['tombaugh_telescope.jpg'], lines: ['He digs a pit twenty-four feet long behind the house. It doubles as the tornado cellar.', 'Down there the temperature holds steady, and glass can be ground to a millionth of an inch.', 'The telescope mount is the crankshaft of his father’s 1910 Buick and parts of a cream separator.', 'Nine inches of mirror. With it he draws Mars and Jupiter at the kitchen table.'] },
    { img: ['kansas_drawings.jpg', 'tombaugh_telescope.jpg'], lines: ['In the autumn he mails the drawings to Lowell Observatory in Flagstaff, Arizona.', 'He only hopes for some advice.', 'The director, V. M. Slipher, sees something else in them: a man with infinite patience.', 'The observatory has a job no senior astronomer wants.'] },
    { img: ['train_station.jpg', 'walk.jpg'], dark: true, lines: ['January 1929.', 'With twenty dollars in his pocket and a one-way ticket on the Santa Fe line, he steps off the train at Flagstaff.', 'The air is thin. The cold bites at his cheeks.', 'His father had said on the platform:', { q: '“Make yourself useful. And beware of easy women.”' }], audio: ['train_arrive'] },
    { img: 'road_climb.jpg', lines: ['A black car is waiting. The driver does not say much.', 'The road climbs slowly up Mars Hill.', 'Only the engine and the creak of snow under the tyres.', 'At the top, an old, slightly forgotten house among the pines. Lowell Observatory.'], loop: 'car_engine_1920s' },
    { img: 'corridor.jpg', lines: ['He is shown inside.', 'The corridors are dark. The floors creak.', 'A red glow leaks from under a door.'], audio: ['door_creak', 'wood_floor_creak'] },
    { img: ['quarters.jpg', 'rest.jpg'], lines: ['The room he is given is small: a bed, a table, one window.', 'Through the window there is only darkness and stars.', 'More stars than he has ever seen in Kansas.', 'Percival Lowell built this place to look for a ninth planet. He died in 1916 without finding it.'] },
    { img: ['astrograph.jpg', 'plate_loading.jpg'], lines: ['The next night, the dome. No heating; warm air would ruin the images.', 'The 13-inch astrograph waits, cold and black.', 'The glass plates are 14 by 17 inches, their surface as sensitive as skin.', 'He learns to stand for an hour at a time, guiding the tube on a single star,', 'so that the exposure does not shift by a tenth of a millimetre.'], audio: ['glass_plate_set'], loop: 'amb_dome' },
    { img: 'comparator.jpg', lines: ['By day he is taken to another room.', 'There stands a large machine of brass and wood. The Zeiss blink comparator.', 'Two plates. The same patch of sky. Different nights.', 'The machine switches the view between them a few times a second.', 'The stars stay still. Anything that moves, jumps.'] },
    { img: 'closeup.jpg', lines: ['His task is simple and cruel:', 'find the one that jumps.', 'Even if it is fainter than a candle three hundred miles away.', 'He does not yet know how long he will sit in this chair.', 'Or whether he will ever find anything at all.'] },
  ],
  tutorial: {
    before: ['February 1929. Dr. Slipher sets two practice plates on the table.', { q: '“There is one asteroid in these. Find it. When you have, mark it and come and get me.”' },
      'The machine shows one plate at a time. Left and right arrows switch between plate A and B, space flips them. Move with W A S D or by dragging with the right mouse button. When something jumps, draw a pencil ring around it.',
      'Work through the plate systematically. The map on the right shows what you have already covered.'],
    after: ['Slipher nods.', { q: '“Yes. But asteroids jump. Planet X creeps. If it exists, it moves barely a minute of arc a day.”' },
      'Lowell believed an unseen mass was tugging at Uranus and Neptune. His last calculation put it somewhere in Gemini.',
      'But the calculation is old, several astronomers have already failed, and few here still believe in it.',
      'In April the real work begins: photographing the ecliptic at opposition, field by field, pair by pair.', 'Every plate gets its label written by hand. Without it, nobody knows what the glass shows.'],
  },
  morning: ['The room is cold. There is frost on the inside of the window.', 'Morning. The coffee pot rattles on the small hot plate.', 'Quiet. Only the clock ticking in the corridor.',
    'Snow fell in the night. The dome roof is white.', 'His fingers are still stiff from yesterday.', 'A letter from his mother. The wheat came up again. Uncle Lee asks about the telescope.',
    'Slipher asks in the corridor how the work is going. The answer is the same as yesterday.', 'He thinks of the pit behind the house in Burdett. It was warmer down there than in this dome.',
    'Ad astra per aspera. To the stars through difficulties. He read it in a book once and did not forget it.'],
  afternoon: ['Afternoon. The comparator room is dim and the machine is waiting.', 'The stack of plates on the table has grown.', 'Footsteps in the corridor, then silence again.',
    'His eyes tire faster than they did yesterday.', 'He wonders how many stars he has looked at. Hundreds of thousands a plate. He stops counting.',
    'Someone in the office says the whole search is a waste of a good telescope. Nobody argues.'],
  evening: ['Evening. Through the window, the pines of Mars Hill and a sky slowly clearing.', 'The coffee is cold. He drinks it anyway.', 'The logbook lies open on the desk.',
    'A few lights burn far below in the town. Up here, none.', 'He reads for a while and falls asleep on the book.', 'He writes home. He does not mention how cold it is.'],
  cold: ['His breath steams.', 'Fingers numb on the slow-motion screw.', 'Wind whistles through the dome slit.', 'The cold rises through the floor and the soles of his boots.', 'The guide star trembles. He corrects.', 'He can no longer feel his toes.', 'Somewhere far off, a coyote.', 'Twenty below. The grease in the drive is stiff tonight.'],
  blinkIdle: ['Click. Click. Click.', 'Stars. Stars. Stars.', 'His eyes begin to see motion that is not there.', 'He leans back, rubs his eyes, leans forward again.', 'The chair creaks.', 'Someone walks past in the corridor. Does not stop.', 'A speck jumps. He holds his breath. A flaw in the emulsion.'],
  weather: {
    clear: ['The sky is clear.', 'Clear and still. The kind of night the programme was built for.', 'Clear. The snow on the Peaks is lit by starlight.'],
    haze: ['Thin high cloud. The stars show through it, dulled.', 'A veil of cirrus. Plates will go deep but not as deep as they should.', 'Hazy. The bright stars have halos.'],
    cloud: ['Overcast.', 'Low cloud sitting on the hill.', 'Grey all day, grey at dusk. Nothing to see.'],
    stormWinter: ['Snow. The road down is gone.', 'A blizzard against the dome. He checks the slit is shut.', 'Snow since noon. The pines creak.'],
    stormSummer: ['Thunder over the Peaks. Rain on the dome.', 'Monsoon cells all evening. Lightning to the south.', 'Rain. It may clear after midnight, it may not.'],
    wind: 'Wind from the southwest. The dome will shake.',
  },
  sketch: {
    Jupiter: 'Sketched Jupiter at the 24-inch: two dark belts, a festoon, the Red Spot pale.', Saturn: 'Sketched Saturn at the 24-inch: the ring shadow sharp, Cassini’s division steady.',
    Mars: 'Sketched Mars at the 24-inch: the polar cap, a dark wedge. Nothing like Lowell’s canals.', Venus: 'Sketched Venus at the 24-inch: a crescent, no markings. Hardly worth the pencil.',
    none: 'No planet worth a pencil tonight. He looked at the Moon instead and felt he was wasting the telescope.',
  },
  logAuto: {
    exposed: (reg, min) => `Exposed ${reg}, ${min} min. Guiding held.`,
    ruined: reg => `${reg}: plate ruined, guiding drifted. Annoying.`,
    developed: n => `Developed ${n} plate${n > 1 ? 's' : ''}. Darkroom cold, the bath slow.`,
    blinked: (reg, d1, d2, n) => `Blinked ${reg} ${d1} / ${d2}. ${n ? n + ' suspect' + (n > 1 ? 's' : '') + '.' : 'Nothing.'}`,
    asteroid: reg => `${reg}: suspect turned out to be an asteroid. Too much motion.`,
    defect: reg => `${reg}: suspect was an emulsion flaw. Not on the third plate.`,
    cloudy: 'Cloudy. No exposures.', moon: 'Moon too bright. No exposures.',
  },
  discovery: {
    lines: ['The object is on plate A.', 'On plate B it has moved. A little. Far too little to be an asteroid.', 'He measures the shift with the micrometer. Three and a half millimetres in six days.',
      'On the third plate the object is exactly where it should be.', 'He sits quietly for about twenty minutes, checking everything again.', 'Then he walks down the corridor to the director’s office.',
      { q: '“Dr. Slipher, I have found your Planet X.”' }],
    quote: 'That’s it.',
  },
  // the story of the search, written in the front of the notebook
  story: [
    'Percival Lowell built this observatory in 1894 to look at Mars. From 1905 he looked for a ninth planet instead, computing where an unseen mass would have to be to pull Uranus and Neptune the way they are pulled. He called it Planet X and put it near Gemini. He died in 1916 without a plate to show.',
    'The 13-inch astrograph was finished in 1929 for one purpose: photograph the whole ecliptic, two plates of every field, and compare them under the Zeiss blink comparator. Stars stay. Asteroids jump. A planet far out creeps a few millimetres in a week.',
    'V. M. Slipher, director, hired a 22-year-old Kansas farm boy on the strength of his planet drawings. The farm boy is you. Exposures are one hour, guided by hand in an unheated dome. Development in the tray by the red lamp. Then the comparator, hundreds of thousands of stars a plate.',
    'Every plate gets a label on its sleeve, written by hand. A pair is two plates of one field, nights apart. A suspect is a ring in pencil. A third plate decides. Nothing is remembered that is not written here.',
  ],
  // quiet moments between the nights
  between: ['He sleeps until the afternoon. Nobody comes up the hill.', 'Snow on the roof of the dome. The pines do not move.', 'The coffee pot, the stove, the window. The same three things every day.',
    'A letter from Burdett. The wheat is in. His father does not ask about the planet.', 'He walks down to Flagstaff for bread and walks back. Nobody asks what he does up there.', 'Slipher passes in the corridor and nods. That is the whole conversation.',
    'He dreams of plates. Thousands of stars, none of them moving.', 'The stove ticks as it cools. Outside, the pines, and above them the thing he is looking for.', 'Sunday. He reads Lowell’s memoir on Planet X again and believes it a little less.',
    'Kansas is a long way off. He has stopped counting the days.', 'The darkroom smells of acetic acid even with the door shut.', 'Two million stars, Slipher says. More by now.'],
  epilogue: [
    { img: ['flagstaff_theatre.jpg', 'rest.jpg'], lines: ['That evening he walks down into Flagstaff and goes to the movies.', 'The following weeks are spent confirming. More plates, more measurements, orbit calculations.', 'The object moves exactly as a distant planet should. Nearly a year of work. Over two million stars compared.'] },
    { img: ['slipher_office.jpg', 'desk.jpg'], lines: ['13 March 1930: Percival Lowell’s birthday, and the anniversary of the discovery of Uranus.', 'Lowell Observatory announces the discovery to the world.', 'More than a thousand name suggestions arrive. Cronus. Minerva. Percival.'] },
    { img: ['venetia.jpg', 'coffee.jpg'], lines: ['The name comes from Venetia Burney, eleven years old, at breakfast in Oxford.', 'Pluto: the god of the underworld, who could make himself invisible.', 'Her grandfather, a librarian, passes it to a professor, who cables Flagstaff.', 'P and L are also Percival Lowell’s initials. The name is adopted on 1 May 1930. Venetia receives five pounds.'] },
    { img: 'portrait.jpg', gray: true, lines: ['Clyde Tombaugh keeps blinking plates for another thirteen years. Hundreds of asteroids, variable stars, clusters. No second planet.', 'He teaches navigation to the Navy during the war, then tracks V-2 rockets at White Sands with telescopes on gun mounts.', 'At New Mexico State University he founds an astronomy department, and in his nineties he still observes from the backyard with the Buick-crankshaft telescope.'] },
    { img: ['new_horizons.jpg', 'walk.jpg'], lines: ['He dies in 1997, aged ninety.', 'In 2006 New Horizons launches with one ounce of his ashes in a canister on its upper deck.', 'The inscription reads: Ad Astra per Aspera.', 'On 14 July 2015 the spacecraft passes Pluto. The bright heart-shaped plain on its surface is named Tombaugh Regio.'] },
  ],
};
